codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: off
      backend:
        base: auto
        flags:
          - backend
      frontend:
        base: auto
        flags:
          - frontend

flags:
  backend:
    paths:
      - "cmd/authelia/"
      - "internal/"
      - "!internal/suites/"
  frontend:
    paths:
      - "web/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no